package pl.javastart.springdata;

public enum Client {
    AMS,
    Apleona,
    Ascentric,
    ATG,
    BLME,
    Colart,
    EA,
    Edrington,
    Eversheds_Sutherland,
    FRS,
    Hargreaves_Lansdown,
    HEE,
    HERE,
    Hospira,
    Immobilien,
    Independent_Vetcare_Limited,
    International_Paint,
    IPC_Media,
    Knight_Frank,
    McKinsey,
    Morrisons,
    Nortal,
    Objectivity,
    Omikron,
    PayU,
    Primark,
    PWC,
    Rant_and_Rave,
    Rolls_Royce,
    SUEZ,
    Techland,
    Telent,
    Tradeteam,
    Unilever
    }
